### PR TITLE
Modified S10setup to move userdata to sdcard on boot if /xbmc-data direc...

### PR DESCRIPTION
**Pull request by toys4me**
...tory exists on sdcard

Mount mSD card as sync, slightly slower write speeds in favor of data integrity.
first partition of sdcard mounted as /mnt/sdcard
Copies all of /tmp/userdata to /mnt/sdcard/xbmc-data/userdata if /xbmc-data directory exists on sdcard
Then bind mounts userdata from sdcard over locations on filesystem to xbmc uses sdcard instead of internal storage.

also........
-Dropbear
Modify S50dropbear to get keys from sdcard if they exist.
With this modification, if you copy your ssh keys from /etc to /media/sdcard/xbmc-data/etc dropbear will use those on boot.
Nice little benefit of not having to clear your cached keys every time you upgrade firmware.

### CODE REVIEW

**Comment by j1nx** [comment]
First of all, I agree with you on the sync mount option if you use it for userdata.

Secondly; What about using the disk label instead of a directory exist check? If LABEL == USERDATA then .....

**Comment by jstobern** [comment]
I personally like the xbmc-data directory check better then the disk label. For some reason I find that it's easier to maintain.

**Comment by j1nx** [comment]
I was thinking about it being "idiot prove". If you have to format a disk, willingly changing the label of the disc to a certain name, makes it less sensitive for error. (I think)

Secondly, was also think of mounting the disk based on that same LABEL (/media/USERDATA) instead of having it mount to usb(x)

Anyway, just some thoughts ;)

**Comment by davilla** [comment]
A) Is there any reason to limit this to SD cards ? I can see a situation where a user has a USB disk with video content and they want to make this the holder of XBMC userdata.

B) Personally, I like the xbmc-data dir existence concept. it's no more or less idiot proof than checking the volume name plus most of our users do not have a clue how to label a disk but making a folder on a disk is within their tech ability. Also this makes testing easier for me and others in that we can use any old sd card

C) The 'xbmc-data' name check needs to be made safe for case issues, xbmc-data, vs Xbmc-data vs XBMC-DATA vs any other combinations. Some OS's will mangle dir names and it helps to not require an case correct name.

**Comment by toys4me** [comment]
Tried USB, all sorts of badness.  Mainly because of usbmount and suspend mode.   USB ports are powered off when suspend mode is entered.  It happens before drives are unmounted.  Then when you resume mount point is invalid and unflushed.   Usbmount then tries to remount drive to a different location.  And won't have volume remounted before xbmc tries to access it.  You just end up with race conditions, corrupted data, and all sorts of things that make life difficult.   So many things would have to be fixed for this to work right, so while possible in the future....its way beyond the scope of a single boot script.  As would need to rework the suspend/resume code in xbmc to make it wait for volume to come back online.

The one things I have been working on (in conjunction with my rewrite of NetworkManager/PosixNetworkmanager/etc) is the ability to have network come up before xbmc and have that userdata stored on your NAS.   But decided to not to hold up V1 of this script while still working out kinks in my wpa_ctrl code.

The reason I went with the xbmc-data concept is that its a doesn't care what type of media volume is.  Could be share, ramdisk, physical media, etc.   It also was easy for a user to turn off and on.   Stick card in PC, create directory, put in XIOS done.    Want to temporarily turn it off and use internal storage, rename the directory.   

One of the things that may not be obvious from this version of the script, is that with this version usbmount basically no longer handles the mounting of first partitions of the sdcard.    The script mounts it, then inserts a line in the fstab, which causes usbmount to not mount it as /media/usb0 on boot.   This solves the problem of usbmount changing the parameters on the /media/sdcard mount, as any time you mounts a volume to another location the last options used applies to all mounts of that volume.

I will go back and fix it so xbmc-data isn't case sensitive.

**Comment by davilla** [comment]
Humm, yes. suspend/resume issues raise their ugly head again. Personally, I never use suspend/resume, these boxes consume less than 5 watts and suspend/resume has other issues besides USB ports. I would have removed suspend/resume for M3/Linux but someone (who shall remain nameless :) wanted me to keep them.

**Comment by toys4me** [comment]
K, updates it a bit.   Its shouldn't care any more on case of xbmc-data, made a change to have dropbear store its keys in /tmp/userdata/etc/dropbear.   I was pointing at /media/sdcard but this way it stores them on sdcard if you have one or in internal memory so both get benefit of not getting annoying key changed messages.
Also tweaked the script so I renable the write cache for the memory card while copying over the userdata info, but then turn cache off when done.  To minimize boot time.

**Comment by davilla** [comment]
ah, what do that last commit have to do with this PR ?

**Comment by toys4me** [comment]
Its was part of update to the branch, part of adding a status screren telling use to now turn off computer, that the files were being copied to the memory card.   Not sure how to update the branch seperate from the pull request.  Do I have to make a new branch?

**Comment by davilla** [comment]
Branches are cheap in git, typically, when doing PRs, you branch and PR that branch. Then leave it alone unless you need to change/add/mod something related to that PR. When you add unrelated stuff, then it become hard to keep things straight and does not cause conflicts with future PRs.

**Comment by davilla** [comment]
I tried NOOP once and the flash file system got very strange.

**Comment by toys4me** [comment]
The big problem with NOOP as that it has no prioritization at all which means  high power thread that is writting alot can completly starve a thread that is trying to read just a few bytes.  Since Deadline puts a priority on read's over writes there its less likely that a program will block on a read while a background thread is busy doing writes.
In the android world there seems to be a whole religion around using NOOP over deadline, which I don't get.   As while it will win in a straight write to disk test, things go sideways in multithreaded read/write scenarios.  As most applications can handle blocking on writes, but very few handle long blocks on read.

**Comment by j1nx** [comment]
@Davilla: Define strange.

I have been using NOOP on other boards and using it for my f16ref build as well, never experienced any problems and always observe a small drop in CPU usage (the scheduling is done by the CPU.)

Disk schedulars were invented because of the needle to move to certain positions for read and write cycles with spinning disks. To speed this up, it is using a schedular to prevent excess movement of the needle, hence putting it in memory / cache.

The enormous speed difference is disk acces between a spinning disk and nand flash basically making it completely unnecessary to use a schedular, hence it is even slower in some cases when it is getting busy.

The problem with nand is that it can only write whole erasureblocks. So even if you write a fraction of data, the whole erasureblock size has to be read into memory, adjusted and written back. I think the problem with DEADLINE is that, if you have a lot of write cycles and you keep letting the read cycles having priority, it can not write back the adjusted erasureblocks fast enough, again causing integrity issues.

A lot of investigation has been done and is still going on within the Linaro group.

I will have a look at your script on the f16ref boxes, with NOOP set as default inside the kernel and report back. You might be right...

**Pull request merged**
