### PR TITLE
Feature: Add support to configure an external ldconfig with menuconfig

### PR DESCRIPTION
**Pull request by JoeKar**
Hi,

this feature could be helpful for people who build their image within a chroot of an "rolling release" distributions (e.g. ArchLinux). It would be a shame, to downgrade a package that much ;).

With my actual glibc v2.17 I'm not able to create the necessary symlinks for a different architecture, so I specify the variable 'BR2_EXTERNAL_LDCONFIG_PATH' with the path to an older package of glibc (v2.10) which has support for different architectures or is missing the feature for excluding different ones.

Maybe this feature could be merged in the future (isn't that essential for the most of the people).

Regards, JoeKar

PS:
Sorry for the 6 commits, they were created while struggling with git. But only 2 files should have changed compared to master.

Sorry for the trouble I've caused to to close and re-creation of pull requests.

### CODE REVIEW

**Comment by davilla** [comment]
@theuni ?

**Comment by theuni** [comment]
Which packages does this cause problems for? ldconfig is essentially useless for cross, and anything depending on it will be broken as a result. I'd rather (as upstream buildroot has done) patch out ldconfig where necessary. Unless you can point to some real need, of course.

**Comment by JoeKar** [comment]
Symlinks aren't created for packages like libsmbclient and if I remember right libamcodec. Maybe some more.
As already mentioned, the most of the people wouldn't need something like that. It makes right now only my life easier, to create all symlinks for the build libs.
But you're right, this can be solved on a different place too.

**Comment by theuni** [comment]
Well I'm not opposed to pulling it in, I just don't want to overcomplicate things if it's not the root of the problem.

Looking at a resulting ld.so.conf, my only entry is for mysql, which we manually append to LD_LIBRARY_PATH during init. ldconfig is never even run on the target. So.. I'm not sure what could be missing by not running it on the builder?

**Comment by JoeKar** [comment]
The real root cause seems to be the missing architecture support (or something like that) in newer builds/packages of ldconfig (glibc). It doesn't seem to be distribution relevant only.
The hint with the external downgrade came from there:
http://buildroot-busybox.2317881.n4.nabble.com/crosstool-buildroot-ldconfig-failure-in-quot-target-finalize-quot-during-build-using-Fedora-13-td21236.html

**Comment by theuni** [comment]
I meant: I'm not sure there's any harm in never running ldconfig on the builder at all.

**Comment by JoeKar** [comment]
I can try next time with commented out ldconfig in the Makefile and will give you the feedback.

**Comment by JoeKar** [comment]
Hi together,

sorry for the long awaiting input. Here I've a comparison between a rootfs with and without ldconfig:

OK: https://gist.github.com/JoeKar/5788609
vs.
NOK: https://gist.github.com/JoeKar/5788610

OR already as diff:
https://gist.github.com/JoeKar/5788629

As you can see, with the first two missing sym-links the system wouldn't run.

Regards, JoeKar

**Comment by davilla** [comment]
https://github.com/vDorst/buildroot-AmLogic/commit/733aad863de09aaca695e775899b2eb621b447fc

**Comment by JoeKar** [comment]
This FR shouldn't be needed anymore, since this commit https://github.com/Pivosgroup/buildroot-linux/commit/2380161f4ecaf233fb42793a7b3172975e16d6e6 of t-nelson...so I will close this FR.

**Pull request closed without merging**
