### PR TITLE
Fix the PKG_CONFIG env variable to be passed in at configure time

### PR DESCRIPTION
**Pull request by josebiro**

### CODE REVIEW

**Comment by theuni** [comment]
This is incorrect. Buildroot sets up all pkg_config variables. Please revert (and remove all pkg_config references here). Not only that, but this will affect other packages as well (all makefiles are sourced).

If pkg_config is not detecting something correctly, it's because the .pc is busted or install in the wrong place. Please fix there as it will affect other packages as well.

In this case, it appears as though the problem is that libcec is checking for udev rather than libudev. If that's the case, it should be patched here and reported/fixed upstream.

**Comment by davilla** [comment]
no, fix it if it's wrong and then we can revert this.
on licid udev.pc is located /usr/share/pkgconfig/udev.pc
also, it's not libcec's configure that can't find it, it's xbmc's configure.

**Comment by davilla** [comment]
the real fix :)
discussion:
http://lists.busybox.net/pipermail/buildroot/2011-March/042187.html
commit:
http://buildroot-busybox.2317881.n4.nabble.com/Problems-with-pkg-config-td24398.html

it is suggested to make clean;make

**Comment by theuni** [comment]
Yes, by 'upstream' I meant libcec.

So, there are several problems here.
1. libudev installs to a non-standard place.
2. buildroot doesn't look in this non-standard place
3. licec checks for udev rather than libudev

We should fix 2. with the above commit, fix 3. upstream (libcec), and report 1. upstream (udev) to find out of there's a reason why.

**Comment by theuni** [comment]
sorry, I misread. I was wrong about 'upstream' (twice ;) so it should be: 3. upstream (xbmc).

**Comment by davilla** [comment]
No, libudev.pc goes to usr/lib/pkgconfig, udev.pc goes to usr/share/pkgconfig. That's standard and proper.
The correct fix if to have buildroot pkg-config look in both. As was fixed in buildroot upstream.

**Comment by theuni** [comment]
looks fine, thanks

**Pull request merged**
