### PR TITLE
Make it possible to configure with libcec

### PR DESCRIPTION
**Pull request by josebiro**

### CODE REVIEW

**Comment by davilla** [comment]
add package/thirdparty/libcec support and xbmc will use it.

**Comment by josebiro** [comment]
That statement could be read several different ways. I was thinking to at least get the library in the build system, without it being flipped on by default. There are still issues with udev to sort out before enabling it in the xbmc configuration.

**Comment by davilla** [comment]
what udev issues ?

**Comment by josebiro** [comment]
For some reason, udev.pc is not installed into the ${system_root}/usr/lib/pkgconfig directory. It's created at build time, but only libudev.pc gets installed. This prevents xbmc configure from finding or using libcec even if it's present.

**Comment by davilla** [comment]
davilla@rootcoder:/xbmc/pivosgroup/buildroot-linux$ cat output/build/udev-173/udev/udev.pc
Name: udev
Description: udev
Version: 173

udevdir=/lib/udev

vs

davilla@rootcoder:/xbmc/pivosgroup/buildroot-linux$ cat output/build/udev-173/libudev/libudev.pc
prefix=/usr
exec_prefix=/usr
libdir=${exec_prefix}/lib
includedir=/usr/include

Name: libudev
Description: Library to access udev device information
Version: 173
Libs: -L${libdir} -ludev -lrt
Libs.private: 
Cflags: -I${includedir}

libudev.pc is the proper pkgconfig to use.

checking this closer.

**Comment by davilla** [comment]
wait

checking config.log

pkg_cv_UDEV_CFLAGS=' '
pkg_cv_UDEV_LIBS='-ludev -lrt  '

it sees libudev fine. in-fact xbmc.bin links to it

0x00000001 (NEEDED)                     Shared library: [libudev.so.0]

So what is the problem ?

**Comment by josebiro** [comment]
from config.log...
configure:24881: checking for CEC
configure:24888: $PKG_CONFIG --exists --print-errors "libcec >= 2.0.0"
configure:24891: $? = 0
configure:24905: $PKG_CONFIG --exists --print-errors "libcec >= 2.0.0"
configure:24908: $? = 0
configure:24922: result: no
Package udev was not found in the pkg-config search path.
Perhaps you should add the directory containing `udev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'udev', required by 'libcec', not found
configure:24938: result: == libcec disabled. CEC adapter support will not be available. ==
configure:25026: == libcec disabled. CEC adapter support will not be available. ==

the libcec checks look for udev and fail when it's not found. Is the right way to fix that to fix the config script?

**Comment by josebiro** [comment]
Paths scrubbed, but by default udev.pc gets installed to share, not lib. from the output of "make udev-install-staging":
 /usr/bin/install -c -m 644 libudev/libudev.pc '$REPO/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/pkgconfig'
 /usr/bin/install -c -m 644 udev/udev.pc '$REPO/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/share/pkgconfig'

worked around the problem by setting a custom PKG_CONFIG_PATH env:
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$REPO/output/staging/usr/share/pkgconfig make
no idea now to make that path permanent in buildroot

-> cat config.log | grep CEC | tail -8
pkg_cv_CEC_CFLAGS='-I$REPO/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/libcec  '
pkg_cv_CEC_LIBS='-lcec  '
CEC_CFLAGS='-I$REPO/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/libcec  '
CEC_LIBS='-lcec  '
LIBCEC_SONAME='libcec.so.2'
USE_CEC_RPI_API='0'
USE_LIBCEC='1'
#define HAVE_LIBCEC 1

**Comment by davilla** [comment]
what host are you compiling under ?

**Comment by josebiro** [comment]
compiling on an Ubuntu 12.10 vm.

**Comment by davilla** [comment]
pushed and fixed in master

**Pull request merged**
